site_name: Документация по проекту Вертер
site_description: Документация по проекту verter-robot

theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search

nav:
  - Главная: index.md
  - Установка:
      - Обзор: v2/installation.md
      - Настройка Ubuntu + ROS2: v2/os_setup.md
      - Настройка udev правил: v2/udev_rules.md
      - Сборка проекта: v2/project_build.md
  - Удалённое подключение: v2/remote_access.md
  - Подключение к WiFi: v2/wifi_connect.md


