slam_toolbox:
  ros__parameters:

    # Solver
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Mode / frames
    mode: mapping
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true

    # Async input
    scan_queue_size: 1
    throttle_scans: 1

    # Map
    resolution: 0.03
    min_laser_range: 0.2
    max_laser_range: 8.0
    map_update_interval: 3.0

    # Scan intake
    minimum_travel_distance: 0.08
    minimum_travel_heading: 0.0873
    minimum_time_interval: 0.05
    check_min_dist_and_heading_precisely: true

    # Scan buffer
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 5.0

    # Scan matching
    use_scan_matching: true
    use_scan_barycenter: true

    # Consecutive scan linking
    link_match_minimum_response_fine: 0.15
    link_scan_maximum_distance: 1.5

    # Loop closure
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Normal correlation search
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Loop closure correlation search
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan matcher penalties/search
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.5

    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.0873
    coarse_angle_resolution: 0.01745

    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    # TF / timing
    transform_publish_period: 0.02
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    restamp_tf: false

    # Runtime
    use_multicore: true
    stack_size_to_use: 40000000
    enable_interactive_mode: true
    debug_logging: false